# site settings
title: Tech Appetite
subtitle:
email: bensewards@outlook.com
description: Delivering sleek user experience applications from the ground up - starting with my bread and butter of Sitecore CMS, Coveo, and frameworks such as Svelte and React.
baseurl: "/tech-appetite" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ben Sewards
street_address: 
city: Gloucester
state: MA
zip_code: 01930
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/bewards
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/bensewards/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
